disabled_rules:
  - todo
  - nesting
  - type_body_length
  - trailing_comma
  - unused_closure_parameter
  - redundant_string_enum_value
  - vertical_parameter_alignment
  - switch_case_alignment

opt_in_rules:
  - force_unwrapping

excluded:
  - Carthage
  - Pods
  - ThirdParty

force_cast: error
force_try: error
force_unwrapping: error

trailing_whitespace:
  ignores_empty_lines: false
  severity: warning
trailing_newline: error
trailing_semicolon: error

comma: error
colon:
  severity: error
opening_brace: error
empty_count: error
legacy_constructor: error
statement_position:
  statement_mode: default
  severity: error
legacy_constant: error

type_name:
  min_length: 4
  max_length:
    warning: 45
    error: 50
  excluded:
    - Url
    - Leg
    - Tag
    - T

identifier_name:
  max_length:
    warning: 50
    error: 60
  min_length:
    error: 3
  excluded:
    - x
    - y
    - dx
    - dy
    - at
    - id
    - db
    - rs
    - to
    - in
    - me
    - us

function_parameter_count:
  warning: 10
  error: 10

line_length:
  warning: 140
  error: 140

function_body_length:
  warning: 150
  error: 200

file_length:
  warning: 1000
  error: 1500

cyclomatic_complexity:
  warning: 30
  error: 40

large_tuple:
  warning: 4
  error: 5

reporter: 'xcode'

custom_rules:
  comments_space:
    name: 'Space After Comment'
    regex: '(^ *//\w+)'
    message: 'There should be a space after //'
    severity: warning

  empty_first_line:
    name: 'Empty First Line'
    regex: '(^[ a-zA-Z ]*(?:protocol|extension|class|struct|func) [ a-zA-Z0-9:,<>\.\(\)\"-=`]*\{\n( *)?\n)'
    message: 'There should not be an empty line after a declaration'
    severity: error

  empty_line_after_guard:
    name: 'Empty Line After Guard'
    regex: '(^ *guard[ a-zA-Z0-9=?.\(\),><!`]*\{[ a-zA-Z0-9=?.\(\),><!`\"]*\}\n *(?!(?:return|guard))\S+)'
    message: 'There should be an empty line after a guard'
    severity: error

  empty_line_after_super:
    name: 'Empty Line After Super'
    regex: '(^ *super\.[ a-zA-Z0-9=?.\(\)\{\}:,><!`\"]*\n *(?!(?:\}|return))\S+)'
    message: 'There should be an empty line after super'
    severity: error

  multiple_empty_lines:
    name: 'Multiple Empty Lines'
    regex: '((?:\s*\n){3,})'
    message: 'There are too many line breaks'
    severity: error
